title: Rahul Autade
logo: /assets/images/Rahul_Autade_Profile_Pic-2.png.png
description: Expertise in Fintech,Payments Innovation, AI Research, Technical Documentation, and Contributions to Global Technology Conferences and Projects.
#show_downloads: true
theme: jekyll-theme-minimal
